import { LangCode } from "./languages";

export interface IntentPattern {
  keywords: RegExp[];
  intent: string;
  priority: number;
}

export interface IntentResponse {
  [lang: string]: string | undefined;
}

export function getResponse(lang: LangCode, intent: string): string {
  const responses: Record<string, IntentResponse> = {
    greeting: {
      en: "Hello! Welcome to TIXSYNC SOLUTIONS. I can help you with cybersecurity, web development, cloud infrastructure, and digital transformation. How can I assist you today?",
      sw: "Karibu TIXSYNC SOLUTIONS! Nipo hapa kukusaidia kuhusu ulinzi wa mtandao, uundaji wa wavuti, miundombinu ya wingu, na mabadiliko ya kidijitali. Nikisaidiaje leo?",
      fr: "Bienvenue chez TIXSYNC SOLUTIONS ! Je peux vous aider avec la cybersecurite, le developpement web, l'infrastructure cloud et la transformation numerique. Comment puis-je vous aider aujourd'hui ?",
      es: "Bienvenido a TIXSYNC SOLUTIONS! Puedo ayudarte con ciberseguridad, desarrollo web, infraestructura en la nube y transformacion digital. Como puedo ayudarte hoy?",
      pt: "Bem-vindo a TIXSYNC SOLUTIONS! Posso ajudar com ciberseguranca, desenvolvimento web, infraestrutura em nuvem e transformacao digital. Como posso ajuda-lo hoje?",
      de: "Willkommen bei TIXSYNC SOLUTIONS! Ich kann Ihnen bei Cybersicherheit, Webentwicklung, Cloud-Infrastruktur und digitaler Transformation helfen. Wie kann ich Ihnen heute helfen?",
      it: "Benvenuto da TIXSYNC SOLUTIONS! Posso aiutarti con sicurezza informatica, sviluppo web, infrastruttura cloud e trasformazione digitale. Come posso aiutarti oggi?",
      nl: "Welkom bij TIXSYNC SOLUTIONS! Ik kan u helpen met cybersecurity, webontwikkeling, cloudinfrastructuur en digitale transformatie. Hoe kan ik u vandaag help?",
      ru: "Dobro pozhalovat v TIXSYNC SOLUTIONS! Ya mogu pomoch vam s kiberbezopasnostyu, veb-razrabotkoy, oblachnoy infrastrukturoy i cifrovoj transformaciej. Chem ya mogu pomoch segodnya?",
      uk: "Laskavo prosymo do TIXSYNC SOLUTIONS! Ya mozhu dopomohty vam z kyberbezpekoyu, web-rozrobkoyu, khmarnoyu infrastrukturoyu ta cyfrovoyu transformatsiyeyu. Chym ya mozhu vam dopomohty sьohodni?",
      zh: "Huanying laidao TIXSYNC SOLUTIONS! Wo keyi bangzhu nin liaojie wangluo anquan, web kaifa, yun jichu shuhua he shuzi zhuanxing. Jintian wo neng wei nin zuo xie shenme?",
      ja: "TIXSYNC SOLUTIONS e youkoso! Saibaeru sekyuriti, web kaihatsu, kuraudo shisetsu, dejitaru toransufoomeshon ni tsuite otetsudai shimasu. Kyou wa donna goyou deshou?",
      ko: "TIXSYNC SOLUTIONS-e osin geul hwanyeonghamnida! Saibeo boan, web gaebal, keulaeu inpeura mit dijiteol jeonhwan-eul dowadeurilkkayo. Oneul museun dowadeurilkkayo?",
      ar: "Ahlan bikum fi TIXSYNC SOLUTIONS! yumkinuni musa'adatukum fi amn al-saybari, tatawwur al-waib, al-bina' al-tahitiyah al-sahabiyah, wa al-tahawwul al-raqami. Kayfa yumkinuni musa'adatukum alyawm?",
      hi: "TIXSYNC SOLUTIONS mein aapka swagat hai! Main cyber suraksha, web vikas, cloud infrastructure aur digital transformation mein aapki sahayata kar sakta hun. Aaj main aapki kaise sahayata kar sakta hun?",
      bn: "TIXSYNC SOLUTIONS-e swagotom! Ami cyber nirokhottha, web unnayan, cloud altya, ebong digital rupantor-e apnake sahajya korbo. Aji ami apnake kibhabe sahajya korte pari?",
      ur: "TIXSYNC SOLUTIONS mein khush amdeed! Main aapki madad kar sakta hun siber security, web development, cloud infrastructure aur digital transformation mein. Aaj main aapki kaise madad kar sakta hun?",
      fa: "Be TIXSYNC SOLUTIONS khosh amadeid! Man mitunam be shoma komak konam dar zamine amniat saiberi, towse'e web, zirsaht abri va tahavole digital. Emrouz chetori mitunam komaketun konam?",
      he: "Bruchim habaim le-TIXSYNC SOLUTIONS! Ani yachol le'ezrachem be-amplei cybor, pituach ashrai, tiknologia anan u-teransformatsia digital. Ech yachol ani le'ezrachem hayom?",
      tr: "TIXSYNC SOLUTIONS'a hos geldiniz! Siber guvenlik, web gelistirme, bulut altyapisi ve donusum konularinda yardimci olabilirim. Bugun size nasil yardimci olabilirim?",
      pl: "Witamy w TIXSYNC SOLUTIONS! Moge pomoc z cyberbezpieczenstwem, tworzeniem stron, infrastruktura chmurowa i transformacja cyfrowa. Jak moge Ci dzis pomoc?",
      cs: "Vitejte v TIXSYNC SOLUTIONS! Mohu vam pomoci s kybernetickou bezpecnosti, vyvojem webu, cloudovou infrastrukturou a digitalni transformaci. Jak vam mohu dnes pomoci?",
      sk: "Vitajte v TIXSYNC SOLUTIONS! Mozem vam pomoct s kybernetickou bezpecnostou, vyvojom webu, cloudovou infrastrukturou a digitalnou transformaciou. Ako vam mozem dnes pomoct?",
      ro: "Bine ati venit la TIXSYNC SOLUTIONS! Pot sa va ajut cu securitate cibernetica, dezvoltare web, infrastructura cloud si transformare digitala. Cum va pot ajuta astazi?",
      hu: "Udvozlom a TIXSYNC SOLUTIONS-nel! Segithetek kiberbiztonsagban, webfejlesztesben, felhoinfrastrukturaban es digitalis atalakitasban. Hogyan segithetek ma?",
      bg: "Dobre doshli v TIXSYNC SOLUTIONS! Mogu da vi pomoqna s kibersebirenost, web razrabotka, oblachna infrastruktura i digitalna transformatsiya. Kak moga da vi pomoqna dnes?",
      hr: "Dobrodosli u TIXSYNC SOLUTIONS! Mogu vam pomoci s kiber sigurnoscu, web razvojem, cloud infrastrukturom i digitalnom transformacijom. Kako vam mogu pomoci danas?",
      sr: "Dobrodosli u TIXSYNC SOLUTIONS! Mogu da vam pomognem sa sajber bezbednoscu, veb razvojem, cloud infrastrukturom i digitalnom transformacijom. Kako mogu da vam pomognem danas?",
      sl: "Dobrodosli v TIXSYNC SOLUTIONS! Lahko vam pomagam z varnostjo, razvojem spleta, oblak infrastrukturo in digitalno preobrazbo. Kako vam lahko danes pomagam?",
      lt: "Sveiki atvyke i TIXSYNC SOLUTIONS! Galiu padeti su kibernetiniu saugumu, ziniatinklio kurimu, debesijos infrastruktura ir skaitmenine transformacija. Kaip galiu jums padeti ssiandien?",
      lv: "Laipni lldzam TIXSYNC SOLUTIONS! Es varu palidzet ar kiberdrosibu, tmekla izstradi, makonu infrastrukturu un digitalo parveidosanu. Ka es varu jums palidzet siodien?",
      et: "Tere tulemast TIXSYNC SOLUTIONS! Ma saan aidata kaitse, veebiarenduse, pilveinfrastruktuuri ja digitaalse transformatsiooniga. Kuidas saan teile tana aidata?",
      fi: "Tervetuloa TIXSYNC SOLUTIONS! Voin auttaa tietoturvan, verkkokehiston, pilvi-infrastruktuurin ja digitaalisen muutoksen kanssa. Kuinka voin auttaa sinua tanaan?",
      sv: "Valkommen till TIXSYNC SOLUTIONS! Jag kan hjalpa dig med cybersakerhet, webbutveckling, molninfrastruktur och digital omstallning. Hur kan jag hjalpa dig idag?",
      no: "Velkommen til TIXSYNC SOLUTIONS! Jeg kan hjelpe deg med cybersikkerhet, webutvikling, skyinfrastruktur og digital transformasjon. Hvordan kan jeg hjelpe deg i dag?",
      da: "Velkommen til TIXSYNC SOLUTIONS! Jeg kan hjalpe dig med cybersikkerhed, webudvikling, cloud-infrastruktur og digital transformation. Hvordan kan jeg hjalpe dig i dag?",
      is: "Velkominn i TIXSYNC SOLUTIONS! Eg get a assistert ther med netoryggi, vefthroun, skyrjathoustu og stafraena umbreytingu. Hvernig get eg adstodad ther i dag?",
      ga: "Failte go TIXSYNC SOLUTIONS! Is feidir liom cabhru leat le sabhailteacht idirlin, forbairt greasanai, bonneagar scamall agus claochlu digiteach. Conas is feidir liom cabhru leat inniu?",
      cy: "Croeso i TIXSYNC SOLUTIONS! Gallaf eich helpu gyda diogelwch rhwydwaith, datblygu gwe, seilwaith cwmwl a thrawsffurmiad digidol. Sut gallaf eich helpu heddiw?",
      mt: "Merhaba fit-TIXSYNC SOLUTIONS! Nista ngbinek bis-sigurtà kibernetika, l-iżvilupp tal-web, l-infrastruttura cloud u t-trasformazzjoni diġitali. Kif nista ngbinek illum?",
      el: "Kalos irthate sto TIXSYNC SOLUTIONS! Boro na sas voithiso me kybernofasfaleia, anaptyxi isto, ypodomi synnefou kai psifikio metaschimatio. Pos boro na sas voithiso simera?",
      ka: "Mogesalmebit TIXSYNC SOLUTIONS-shi! Me var chemo dahekopit kiberusepnoebebis, web ganvitarebis, vrulobis infrastrukturisa da cifruli transformaciis. Dges ra mevar chemo dahekopit?",
      hy: "Barev galust TIXSYNC SOLUTIONS! Yes karogh em ognel kiberanvutyan, vev macman, ambain yntakarutsyan ev tsvayin paterutsyan masin. Aysor inchpes karogh em ognel dust?",
      az: "TIXSYNC SOLUTIONS-a xosh geldiniz! Men kibertehlukesizlik, web inkiyaf, bulud altyapisi ve reqemsal transformasiya sahesinde komek ede bilerem. Bu gun size neme komek ede bilerem?",
      kk: "TIXSYNC SOLUTIONS-q qos kelldiniz! Men kiberqauepsizdik, web aparw, buluttwq infraqurwlm wndiqw transformatziya boyinsha komek ete alamin. Bugun sizge qalay komek ete alamin?",
      uz: "TIXSYNC SOLUTIONS ga xush kelibsiz! Men kiberxavfsizlik, veb dasturlash, bulut infratuzilmasi va raqamli transformatsiya bo'yicha yordam bera olaman. Bugun sizga qanday yordam bera olaman?",
      mn: "TIXSYNC SOLUTIONS-d tutaig morilno uu! Bi kiber ariigvi baidal, web huuheel, uleen deed buets toon huuruulalti tusaltsakh bolomjtoi. Uurduu taand helcee tuslaaj chadakh ve?",
      ne: "TIXSYNC SOLUTIONS ma swagat cha! Ma tapailai cyber suraksha, web vikas, cloud infrastructure ra digital transformation ma sahayata garna sakchu. Aaja ma tapailai kasari sahayata garna sakchu?",
      th: "Yin dee ton rub TIXSYNC SOLUTIONS! Chan chuai dai rueang ngeun park cyber, development web, infrastructure cloud, lae kan plian plaeng digital. Wan nee chan chuai arai dai?",
      vi: "Chao mung den voi TIXSYNC SOLUTIONS! Toi co the giup ban ve an mang mang, phat trien web, ha tang may tinh va chuyen doi so. Hom nay toi co the giup ban dieu gi?",
      id: "Selamat datang di TIXSYNC SOLUTIONS! Saya bisa membantu Anda dengan keamanan siber, pengembangan web, infrastruktur cloud, dan transformasi digital. Apa yang bisa saya bantu hari ini?",
      ms: "Selamat datang ke TIXSYNC SOLUTIONS! Saya boleh membantu anda dengan keselamatan siber, pembangunan web, infrastruktur awan, dan transformasi digital. Apa yang boleh saya bantu hari ini?",
      tl: "Maligayang pagdating sa TIXSYNC SOLUTIONS! Matutulungan kita sa cybersecurity, web development, cloud infrastructure, at digital transformation. Paano kita matutulungan ngayon?",
      am: "Eyakabarew wed TIXSYNC SOLUTIONS! EzeyhonAy makedasqwe sir sayerbar medhanit, web litmariyet, klayod infrasturukcher, akilk digital metekeliyalew. Qen new eyayhon le metekeliyalew addis ale?",
      ha: "Barka da zuwa TIXSYNC SOLUTIONS! Zan iya taimaka muku tare da amincin cybersecurity, ci gaban yanar gizo, injin gogashiya, da canza-dijital. Yadda za a taimaka muku yau?",
      yo: "E ku abo si TIXSYNC SOLUTIONS! Mo le ran yin lowo nipa aabo ayelujara, development eyan-ayan, infrastruti aabo, ati atunto digital. Bawo ni mo le ran yin lowo lola?",
      ig: "Nnoo na TIXSYNC SOLUTIONS! Ana m aka gị aka nchekwa ndo, mmepe webusaiti, infrastructure egwuregwu, na mgbanwe ngwa ngwa ojugha. Kedu ka m nwere ike inyere gika taa?",
      zu: "Sawubona ku-TIXSYNC SOLUTIONS! Ngingakusiza ngokuphepha kwe-cyber, ukuthuthukisa i-web, ukuhlinzekwa kwamakhulu, nokuguqulwa kwedijithali. Ngingakusiza kanjani namuhla?",
      xh: "Molo ku-TIXSYNC SOLUTIONS! Ndinokukunceda ngokhuseleko lwe-cyber, ukuphucula iwebhu, uncedo lwekhowudi, kunye nokuguqulwa kobuchwephesha. Ndinokunceda njani namhlanje?",
      af: "Welkom by TIXSYNC SOLUTIONS! Ek kan jou help met kubersekuriteit, webontwikkeling, wolkinfrastruktuur en digitale transformasie. Hoe kan ek jou vandag help?",
      so: "Ku soo dhawoow TIXSYNC SOLUTIONS! Waxaan ku caawin karaa amniga cyber-ka, horumarinta web-ka, kaabayaasha darawalada, iyo bedelka dhijitaalka. Sidee aan kuu caawin karaa maanta?",
      rw: "Murakaza neza mu TIXSYNC SOLUTIONS! Ndabona kukugufasha mu bushyingo bwikoresha rya interineti, iterambere ryurubuga, ubufatanye bwamabwiriza, no guhinduranya kwadijitali. Dukorera iki uyu munsi?",
      mg: "Tonga soa eto aminny TIXSYNC SOLUTIONS! Afaka manampy anao aminny fiarovana aminny Internet, fanambadiana tranonkala, rafitra aminny alavan-kabary, ary fanovana avidy. Ahoana no afaka manampy anao androany?",
      st: "Re a leboha mo TIXSYNC SOLUTIONS! Ke u thusa le polokeho ya cyber, nts'etsopele ya web, rafsterya ya di-cloud, le phetoho ya di-digital. Ke u thusa jwang kajeno?",
      sn: "Mhoro ku-TIXSYNC SOLUTIONS! Ndingakubatsira nezve security ye-cyber, kugadzirisa web, infrastructure ye-cloud, uye shanduko ye-digital. Ndingakubatsira sei nhasi?",
      eo: "Bonvenon en TIXSYNC SOLUTIONS! Mi povas helpi vin pri cifereca sekureco, retejprogramado, nuboinfrastrukturo, kaj cifereca transformigo. Kiel mi povas helpi vin hodiau?",
      la: "Salve apud TIXSYNC SOLUTIONS! Ego possum adiuvare te de securitate cyber, evolutione retis, infrastruktura nubium, et transformatione digitali. Quomodo te hodie adiuvare possum?",
      ca: "Benvingut a TIXSYNC SOLUTIONS! Puc ajudar-te amb ciberseguretat, desenvolupament web, infraestructura al vol i transformacio digital. Com et puc ajudar avui?",
      eu: "Ongi etorri TIXSYNC SOLUTIONS-era! Zure kibersegurtasunean, web garapenean, hodei azpiegituran eta eraldaketa digitalean lagundu dezaket. Nola lagun zaitzake gaur?",
      gl: "Benvido a TIXSYNC SOLUTIONS! Podo axudarche con ciberseguridade, desenvolvemento web, infraestrutura na nube e transformacion dixital. Como che podo axudar hoxe?",
      co: "Bonghjornu a TIXSYNC SOLUTIONS! Posso aiutavi cun sicurezza cyber, sviluppu web, infrastruttura cloud e trasformazione digitale. Cemu posso aiutavvi assai?",
      fy: "Wolkom by TIXSYNC SOLUTIONS! Ik kin jo helpje mei cybersecurity, webûntwikkeling, wolkynfrastruktuer en folsleine transformatie. Hoe kin ik jo hielpe?",
      lb: "Wëllkomm bei TIXSYNC SOLUTIONS! Ech kann Iech hëllefen mat Cybersécherheet, Webentwécklung, Cloud-Infrastruktur an digitaler Transformatioun. Wéi kann ech Iech haut hëllefen?",
      mk: "Dobredojdovte vo TIXSYNC SOLUTIONS! Moze da vam pomoam so sajber bezbednost, web razvoj, oblak infrastruktura i digitalna transformacija. Kakov moze da vam pomognam denes?",
      sq: "Mirë se vini në TIXSYNC SOLUTIONS! Mund t'ju ndihmoj me sigurinë kibernetike, zhvillimin e uebit, infrastrukturën e resë dhe transformimin dixhital. Si mund t'ju ndihmoj sot?",
      bs: "Dobrodosli u TIXSYNC SOLUTIONS! Mogu vam pomoći sa kiber sigurnoscu, web razvojem, cloud infrastrukturom i digitalnom transformacijom. Kako vam mogu pomoći danas?",
      mi: "Nau mai ki TIXSYNC SOLUTIONS! Ka taea e au te awhina i te haumarotanga tukutuku, te whanake tukutuku, te hanganga aputi, me te huringa turuki. Me pehea taku awina i a koe i tenei ra?",
      haw: "E komo mai i TIXSYNC SOLUTIONS! Hiki ia oe ke koku ia oe i ka paleka eleu, ka hoohana punaewele, ka hookele wiwi, a me ka loli eleu. Pehea au e hiki ke koku i oe i kela la?",
      sm: "Fakatalofa atu i TIXSYNC SOLUTIONS! E mafai ona ou fesoasoani i le siosiomaga, fausiga tuku, faiga polokalame, ma le suesuega. O le a fesoasoani atu au i le aso nei?",
      to: "Talofa mai ki TIXSYNC SOLUTIONS! Ko e kou fakaaoga mo he polokalame, fakaola tuku, fakaola fakamatala, ma fakafofounga digitaalu. Ko e hou fakaaoga ki a koe he aho ni?",
      fj: "Ni sa bula vinaka e TIXSYNC SOLUTIONS! Au na vakayagataka kina i na dina na cuuna, na veitaroiti, na dina ni tabu, kei na vakayagataki na wauciwuci. Au na yawa vakacava e na rai tuccea?",
      ny: "Moni bwanji ku TIXSYNC SOLUTIONS! Ndili pano kuti ndikuthandize chitetezo cha cyber, kupanga masamba, thupi la pansi, ndi kusintha digito. Ndingakuthandizeni bwanji lero?",
      wo: "Dalal jamm ci TIXSYNC SOLUTIONS! Maa ngi ci biir taim yi ngir dimbal la wir al cybersecurity, al development web, al infrastructure cloud, al transformation digitale. Nan leen maangi def tey?",
      ff: "Jam ngir TIXSYNC SOLUTIONS! Mi dulaani haa maa ngir balla al security, al development web, al infrastructure cloud, al transformation digitale. Nano mi maa ballaano bissaa?",
      bm: "I ni ce TIXSYNC SOLUTIONS! Ne na wa kɛ kɔnɔ ti nafa ye cybersecurity, web development, cloud infrastructure, ne digital transformation. N bɛ kɛ fɛɛ nafa dɛn kɛ na?",
      lg: "Nkulamusaniddde ku TIXSYNC SOLUTIONS! Njagala okukuyamba ku kibuzibuzi, okusinziira ku webu, ne ku ngeri yobuyinza, ne mu kisoolizo kyadigital. Nze nolaba ki nnyini leero?",
      rn: "Murakaza neza mu TIXSYNC SOLUTIONS! Ndabona kukugufasha mu bushyingo bwikoresha rya interineti, iterambere ryurubuga, ubufatanye bwamabwiriza, no guhinduranya kwadijitali. Dukorera iki uyu munsi?",
      lo: "Sabaidee bon TIXSYNC SOLUTIONS! Khoi pen chuai khun rueang ngeun park cyber, development web, infrastructure cloud, lae kan plian plaeng digital. Wan nee khoi chuai arai dai?",
      km: "Suosdei nak TIXSYNC SOLUTIONS! Knyom chhouy banhch hear tae knong security cyber, development web, infrastructure cloud, ne Transformation digital. Knyom chhouy banhch hear tae mok mok leey?",
      bo: "TIXSYNC SOLUTIONS la tashi delek! Nga de re tusaltsakh nyi cyber bde ba, web gsar bpa, sa bon rtsa, dang po rgyu bsgyur bde ba nyi madod par grol dgos na ga?",
      dz: "TIXSYNC SOLUTIONS la kuzu zangpo! Nga kyi gral gyed nus na ga cybersecurity, web development, cloud infrastructure, digital transformation du. Khyed rang la gral gyed nus na ga?",
    },
    services: {
      en: "TIXSYNC SOLUTIONS offers a comprehensive suite of technology services:\n\n1. **Cybersecurity**: Penetration Testing, SOC Operations, Security Audits, Incident Response, SIEM, Firewalls, Vulnerability Assessments\n2. **Web Development**: React, Next.js, Node.js, TypeScript, Python, full-stack applications, e-commerce platforms\n3. **Cloud Infrastructure**: AWS, Azure, GCP, migration, serverless architecture, Docker, Kubernetes\n4. **Digital Transformation**: Business process automation, system integration, workflow optimization\n5. **Compliance**: ISO 27001, GDPR, regulatory adherence, security policies\n6. **DevOps**: CI/CD pipelines, GitHub Actions, Jenkins, Terraform, Ansible\n7. **Mobile Development**: React Native, Flutter, iOS and Android apps\n\nWe serve clients across Africa from our base in Kenya. What specific service interests you?",
      sw: "TIXSYNC SOLUTIONS inatoa huduma kamili za teknolojia:\n\n1. **Ulinzi wa Mtandao**: Majaribio ya Uvamizi, Operesheni za SOC, Ukaguzi wa Usalama, Mshughulikiajo wa Matukio, SIEM, Motoa, Tathmini za Upvu\n2. **Uundaji wa Vavuti**: React, Next.js, Node.js, TypeScript, Python, programu za kamili, majukwaa ya biashara\n3. **Miundombinu ya Wingu**: AWS, Azure, GCP, uhamishaji, usanidi wa bila huduma, Docker, Kubernetes\n4. **Mabadiliko ya Dijitali**: Uboreshaji wa mchakato wa biashara, muunganisho wa mifumo, uboreshaji wa kazi\n5. **Uzingatiaji**: ISO 27001, GDPR, kufuata kanuni, sera za usalama\n6. **DevOps**: Mitirio ya CI/CD, GitHub Actions, Jenkins, Terraform, Ansible\n7. **Uundaji wa Simu**: React Native, Flutter, programu za iOS na Android\n\nTunahudumia wateja kote Afrika kutoka maskani yetu nchini Kenya. Huduma gani maalum inakuvutia?",
      fr: "TIXSYNC SOLUTIONS propose une suite complete de services technologiques :\n\n1. **Cybersecurite** : Tests de Penetration, Operations SOC, Audits de Securite, Reponse aux Incidents, SIEM, Pare-feu, Evaluations de Vulnerabilite\n2. **Developpement Web** : React, Next.js, Node.js, TypeScript, Python, applications full-stack, plates-formes e-commerce\n3. **Infrastructure Cloud** : AWS, Azure, GCP, migration, architecture serverless, Docker, Kubernetes\n4. **Transformation Numerique** : Automatisation des processus metier, integration des systemes, optimisation des flux de travail\n5. **Conformite** : ISO 27001, GDPR, respect de la reglementation, politiques de securite\n6. **DevOps** : Pipelines CI/CD, GitHub Actions, Jenkins, Terraform, Ansible\n7. **Developpement Mobile** : React Native, Flutter, applications iOS et Android\n\nNous servons des clients a travers l'Afrique depuis notre base au Kenya. Quel service vous interesse ?",
      es: "TIXSYNC SOLUTIONS ofrece un conjunto completo de servicios tecnologicos:\n\n1. **Ciberseguridad**: Pruebas de Penetracion, Operaciones SOC, Auditorias de Seguridad, Respuesta a Incidentes, SIEM, Firewalls, Evaluaciones de Vulnerabilidad\n2. **Desarrollo Web**: React, Next.js, Node.js, TypeScript, Python, aplicaciones full-stack, plataformas e-commerce\n3. **Infraestructura en la Nube**: AWS, Azure, GCP, migracion, arquitectura serverless, Docker, Kubernetes\n4. **Transformacion Digital**: Automatizacion de procesos empresariales, integracion de sistemas, optimizacion de flujos de trabajo\n5. **Cumplimiento**: ISO 27001, GDPR, cumplimiento normativo, politicas de seguridad\n6. **DevOps**: Pipelines CI/CD, GitHub Actions, Jenkins, Terraform, Ansible\n7. **Desarrollo Movil**: React Native, Flutter, aplicaciones iOS y Android\n\nAtendemos clientes en toda Africa desde nuestra base en Kenia. Que servicio especifico le interesa?",
      de: "TIXSYNC SOLUTIONS bietet ein umfassendes Sortiment an Technologiedienstleistungen:\n\n1. **Cybersicherheit**: Penetrationstests, SOC-Operationen, Sicherheitsaudits, Incident-Response, SIEM, Firewalls, Schwachstellenbewertungen\n2. **Webentwicklung**: React, Next.js, Node.js, TypeScript, Python, Full-Stack-Anwendungen, E-Commerce-Plattformen\n3. **Cloud-Infrastruktur**: AWS, Azure, GCP, Migration, Serverless-Architektur, Docker, Kubernetes\n4. **Digitale Transformation**: Automatisierung von Geschaftsprozessen, Systemintegration, Workflow-Optimierung\n5. **Compliance**: ISO 27001, GDPR, regulatorische Einhaltung, Sicherheitsrichtlinien\n6. **DevOps**: CI/CD-Pipelines, GitHub Actions, Jenkins, Terraform, Ansible\n7. **Mobile Entwicklung**: React Native, Flutter, iOS- und Android-Apps\n\nWir bedienen Kunden in ganz Afrika von unserem Standort in Kenia aus. Welcher Service interessiert Sie?",
      pt: "TIXSYNC SOLUTIONS oferece um conjunto abrangente de servicos de tecnologia:\n\n1. **Ciberseguranca**: Testes de Penetracao, Operacoes SOC, Auditorias de Seguranca, Resposta a Incidentes, SIEM, Firewalls, Avaliacoes de Vulnerabilidade\n2. **Desenvolvimento Web**: React, Next.js, Node.js, TypeScript, Python, aplicacoes full-stack, plataformas e-commerce\n3. **Infraestrutura em Nuvem**: AWS, Azure, GCP, migracao, arquitetura serverless, Docker, Kubernetes\n4. **Transformacao Digital**: Automacao de processos de negocios, integracao de sistemas, otimizacao de fluxos de trabalho\n5. **Conformidade**: ISO 27001, GDPR, aderencia regulamentar, politicas de seguranca\n6. **DevOps**: Pipelines CI/CD, GitHub Actions, Jenkins, Terraform, Ansible\n7. **Desenvolvimento Movil**: React Native, Flutter, aplicacoes iOS e Android\n\nAtendemos clientes em toda a Africa a partir da nossa base no Quenia. Qual servico especifico te interessa?",
    },
    cybersecurity: {
      en: "Our cybersecurity services provide comprehensive protection for your organization:\n\n- **Penetration Testing**: Simulated attacks to find vulnerabilities before hackers do\n- **SOC Operations**: 24/7 Security Operations Center monitoring and threat detection\n- **Security Audits**: Complete assessment of your security posture and compliance\n- **Incident Response**: Rapid response to security breaches and data incidents\n- **SIEM Implementation**: Security Information and Event Management system deployment\n- **Firewall Management**: Configuration, monitoring, and optimization of network firewalls\n- **Vulnerability Assessments**: Regular scanning and identification of security weaknesses\n\nWe serve organizations across Africa from Kenya. Need a security consultation? Contact us at tixsyncsolutions@gmail.com or +254704440164.",
      sw: "Huduma zetu za ulinzi wa mtandao hutoa ulinzi kamili kwa shirika lako:\n\n- **Majaribio ya Uvamizi**: Mashambulizi ya kuigwa ili kupata upvu kabla ya waovamizi\n- **Operesheni za SOC**: Ufuatiliaji wa Kituo cha Ulinzi wa Usalama 24/7 na utambuzi wa vitisho\n- **Ukaguzi wa Usalama**: Tathmini kamili ya hali yako ya usalama na uzingatiaji\n- **Mshughulikiajo wa Matukio**: Majibu ya haraka kwa ukiukaji wa usalama na matukio ya data\n- **Uwekaji wa SIEM**: Uwekaji wa mfumo wa Usimamizi wa Taarifa za Usalama na Matukio\n- **Usimamizi wa Motoa**: Usanidi, ufuatiliaji, na uboreshaji wa motoa wa mtandao\n- **Tathmini za Upvu**: Uchunguzi wa kawaida na utambuzi udhaifu wa usalama\n\nTunahudumia mashirika kote Afrika kutoka Kenya. Unahitaji ushauri wa usalama? Tuandikie kwa tixsyncsolutions@gmail.com au piga +254704440164.",
      fr: "Nos services de cybersecurite offrent une protection complete pour votre organisation :\n\n- **Tests de Penetration** : Atsimules pour trouver les vulnerabilites avant les pirates\n- **Operations SOC** : Surveillance du Centre d'Operations de Securite 24h/24 et detection des menaces\n- **Audits de Securite** : Evaluation complete de votre posture de securite et conformite\n- **Reponse aux Incidents** : Reponse rapide aux violations de securite et incidents de donnees\n- **Implementation SIEM** : Deploiement du systeme de gestion des informations et evenements de securite\n- **Gestion des Pare-feu** : Configuration, surveillance et optimisation des pare-feu reseau\n- **Evaluations de Vulnerabilite** : Analyse reguliere et identification des faiblesses de securite\n\nNous servons des organisations a travers l'Afrique depuis le Kenya. Besoin d'une consultation securite ? Contactez-nous a tixsyncsolutions@gmail.com ou appelez le +254704440164.",
      es: "Nuestros servicios de ciberseguridad brindan proteccion integral para su organizacion:\n\n- **Pruebas de Penetracion**: Ataques simulados para encontrar vulnerabilidades antes que los hackers\n- **Operaciones SOC**: Monitoreo del Centro de Operaciones de Seguridad 24/7 y deteccion de amenazas\n- **Auditorias de Seguridad**: Evaluacion completa de su postura de seguridad y cumplimiento\n- **Respuesta a Incidentes**: Respuesta rapida a violaciones de seguridad e incidentes de datos\n- **Implementacion SIEM**: Despliegue del sistema de gestion de informacion y eventos de seguridad\n- **Gestion de Firewalls**: Configuracion, monitoreo y optimizacion de firewalls de red\n- **Evaluaciones de Vulnerabilidad**: Escaneo regular e identificacion de debilidades de seguridad\n\nAtendemos organizaciones en toda Africa desde Kenya. Necesita una consulta de seguridad? Contactenos en tixsyncsolutions@gmail.com o llame al +254704440164.",
      de: "Unsere Cybersicherheitsdienste bieten umfassenden Schutz fur Ihre Organisation:\n\n- **Penetrationstests**: Simulierte Angriffe, um Schwachstellen zu finden, bevor Hacker es tun\n- **SOC-Operationen**: 24/7-Überwachung des Security Operations Center und Bedrohungserkennung\n- **Sicherheitsaudits**: Vollstandige Bewertung Ihrer Sicherheitslage und Compliance\n- **Incident-Response**: Schnelle Reaktion auf Sicherheitsverletzungen und Daten Zwischenfalle\n- **SIEM-Implementierung**: Bereitstellung des Security Information and Event Management Systems\n- **Firewall-Management**: Konfiguration, Uberwachung und Optimierung von Netzwerk-Firewalls\n- **Schwachstellenbewertungen**: Regelmassige Scanning und Identifizierung von Sicherheitslucken\n\nWir bedienen Organisationen in ganz Afrika von Kenia aus. Benotigen Sie eine Sicherheitsberatung? Kontaktieren Sie uns unter tixsyncsolutions@gmail.com oder rufen Sie +254704440164 an.",
      it: "I nostri servizi di sicurezza informatica offrono protezione completa per la tua organizzazione:\n\n- **Test di Penetrazione**: Attacchi simulati per trovare vulnerabilita prima che i pirati informatici lo facciano\n- **Operazioni SOC**: Monitoraggio 24/7 del Centro Operazioni di Sicurezza e rilevamento delle minacce\n- **Audit di Sicurezza**: Valutazione completa della tua postura di sicurezza e conformita\n- **Risposta agli Incidenti**: Risposta rapida alle violazioni della sicurezza e agli incidenti dati\n- **Implementazione SIEM**: Distribuzione del sistema di gestione delle informazioni e degli eventi di sicurezza\n- **Gestione dei Firewall**: Configurazione, monitoraggio e ottimizzazione dei firewall di rete\n- **Valutazioni delle Vulnerabilita**: Scansione regolare e identificazione delle debolezze di sicurezza\n\nServiamo organizzazioni in tutta Africa dal nostro base in Kenia. Hai bisogno di una consulenza sulla sicurezza? Contattaci a tixsyncsolutions@gmail.com o chiama +254704440164.",
    },
    pricing: {
      en: "Our pricing is customized based on your specific needs and project scope:\n\n- **Starting Packages**: From KES 50,000\n- **Typical Projects**: KES 100,000 - 500,000\n- **Enterprise Solutions**: Custom pricing based on requirements\n\nFactors that influence pricing:\n- Project complexity and timeline\n- Number of services required\n- Level of support and maintenance needed\n- Scale of implementation\n\nFor an accurate quote tailored to your needs, please contact us at:\n- Email: tixsyncsolutions@gmail.com\n- Phone: +254704440164\n\nWe offer free initial consultations to understand your requirements.",
      sw: "Bei zetu zimetolewa kulingana na mahitaji yako maalum na upekee wa mradi:\n\n- **Vifuruto vya Kuanza**: Kuanzia KES 50,000\n- **Miradi ya Kawaida**: KES 100,000 - 500,000\n- **Suluhisho za Biashara**: Bei maalum kulingana na mahitaji\n\nSababu zinazoathiri bei:\n- Uchunguzi wa mradi na ratiba\n- Idadi ya huduma zinazohitajika\n- Kiwango cha msaada na matengenezo yanayohitajika\n- Kiwango utekelezaji\n\nKwa nukta sahihi iliyobinafsishwa kwa mahitaji yako, tafadhali tuandikie kwa:\n- Barua pepe: tixsyncsolutions@gmail.com\n- Simu: +254704440164\n\nTunatoa ushauri wa bure wa kwanza kuelewa mahitaji yako.",
      fr: "Nos tarifs sont personnalises selon vos besoins specifiques et l'ampleur du projet :\n\n- **Formules de depart** : A partir de 50 000 KES\n- **Projets typiques** : 100 000 - 500 000 KES\n- **Solutions d'entreprise** : Tarification personnalisee selon les exigences\n\nFacteurs influencant le tarif :\n- Complexite du projet et calendrier\n- Nombre de services requis\n- Niveau de support et de maintenance necessaire\n- Echelle de mise en oeuvre\n\nPour un devis precise adapte a vos besoins, contactez-nous a :\n- Email : tixsyncsolutions@gmail.com\n- Telephone : +254704440164\n\nNous offrons des consultations initiales gratuites pour comprendre vos besoins.",
      es: "Nuestros precios se personalizan segun sus necesidades especificas y el alcance del proyecto:\n\n- **Paquetes de inicio**: Desde KES 50,000\n- **Proyectos tipicos**: KES 100,000 - 500,000\n- **Soluciones empresariales**: Precios personalizados segun requisitos\n\nFactores que influyen en el precio:\n- Complejidad del proyecto y cronograma\n- Cantidad de servicios requeridos\n- Nivel de soporte y mantenimiento necesario\n- Escala de implementacion\n\nPara una cotizacion precisa adaptada a sus necesidades, contactenos en:\n- Email: tixsyncsolutions@gmail.com\n- Telefono: +254704440164\n\nOfrecemos consultas iniciales gratuitas para entender sus requisitos.",
      de: "Unsere Preise werden individuell nach Ihren spezifischen Bedurfnissen und dem Projektumfang kalkuliert:\n\n- **Einstiegspakete**: Ab KES 50.000\n- **Typische Projekte**: KES 100.000 - 500.000\n- **Unternehmenslosungen**: Individuelle Preise basierend auf Anforderungen\n\nPreisbeeinflussende Faktoren:\n- Projektkomplexitat und Zeitplan\n- Anzahl der erforderlichen Dienstleistungen\n- Benotigtes Support- und Wartungsniveau\ n- Umfang der Implementierung\n\nFur ein massgeschneidertes Angebot kontaktieren Sie uns bitte unter:\n- E-Mail: tixsyncsolutions@gmail.com\n- Telefon: +254704440164\n\nWir bieten kostenlose Erstberatungen, um Ihre Anforderungen zu verstehen.",
    },
    about: {
      en: "TIXSYNC SOLUTIONS is a technology company founded by Cornelius Maina Nyaga, based in Kenya and serving clients across Africa.\n\n**Our Mission**: To protect and empower businesses across Africa through innovative technology solutions.\n\n**Key Facts**:\n- Founded in Kenya, serving the entire African continent\n- Specializes in cybersecurity, web development, cloud infrastructure, and digital transformation\n- Committed to building secure, scalable, and modern systems\n- Team of skilled professionals with expertise across multiple technology domains\n\n**Our Approach**:\nWe combine deep technical expertise with a thorough understanding of African business needs to deliver solutions that are both globally competitive and locally relevant.\n\nContact us at tixsyncsolutions@gmail.com or +254704440164 to learn more.",
      sw: "TIXSYNC SOLUTIONS ni kampuni ya teknolojia iliyoanzishwa na Cornelius Maina Nyaga, yenye maskani yake nchini Kenya na inayohudumia wateja kote Afrika.\n\n**Dhamira yetu**: Kulinda na kuwezesha biashara kote Afrika kupitia suluhisho za teknolojia ya ubunifu.\n\n**Uhalisia Muhimu**:\n- Ilianzishwa Kenya, inayohudumia bara lote la Afrika\n- Inataalamu katika ulinzi wa mtandao, uundaji wa wavuti, miundombinu ya wingu, na mabadiliko ya kidijitali\n- Kujitolea kujenga mifumo salama, inayoweza kupanuliwa, ya kisasa\n- Timu ya wataalamu wenye ujuzi katika nyanja nyingi za teknolojia\n\n**Mbinu yetu**:\nTunachanganya utaalamu mkubwa wa kiufundi na uelewa wa kina wa mahitaji ya biashara ya Afrika ili kutoa suluhisho ambalo ni la kimataifa na linalofaa hapa.\n\nTuandikie kwa tixsyncsolutions@gmail.com au +254704440164 kujua zaidi.",
      fr: "TIXSYNC SOLUTIONS est une entreprise technologique fondee par Cornelius Maina Nyaga, basee au Kenya et servant des clients a travers l'Afrique.\n\n**Notre mission** : Proteger et autonomiser les entreprises a travers l'Afrique grace a des solutions technologiques innovantes.\n\n**Faits cles** :\n- Fondee au Kenya, servant tout le continent africain\n- Specialisee en cybersecurite, developpement web, infrastructure cloud et transformation numerique\n- Engagee a construire des systemes securises, evolutifs et modernes\n- Equipe de professionnels competents avec une expertise dans de nombreux domaines technologiques\n\n**Notre approche** : Nous combinons une expertise technique approfondie avec une comprehension approfondie des besoins des entreprises africaines pour fournir des solutions a la fois mondialement competitives et localement pertinentes.\n\nContactez-nous a tixsyncsolutions@gmail.com ou +254704440164 pour en savoir plus.",
      es: "TIXSYNC SOLUTIONS es una empresa tecnologica fundada por Cornelius Maina Nyaga, con sede en Kenia y atendiendo clientes en toda Africa.\n\n**Nuestra mision**: Proteger y empoderar a las empresas en toda Africa a traves de soluciones tecnologicas innovadoras.\n\n**Datos clave**:\n- Fundada en Kenia, atendiendo a todo el continente africano\n- Se especializa en ciberseguridad, desarrollo web, infraestructura en la nube y transformacion digital\n- Comprometida a construir sistemas seguros, escalables y modernos\n- Equipo de profesionales capacitados con experiencia en multiples dominios tecnologicos\n\n**Nuestro enfoque**: Combinamos una profunda experiencia tecnica con un entendimiento profundo de las necesidades empresariales africanas para ofrecer soluciones que sean globalmente competitivas y localmente relevantes.\n\nContactenos en tixsyncsolutions@gmail.com o +254704440164 para saber mas.",
      de: "TIXSYNC SOLUTIONS ist ein Technologieunternehmen, gegrundet von Cornelius Maina Nyaga, mit Sitz in Kenia und bedient Kunden in ganz Afrika.\n\n**Unsere Mission**: Unternehmen in ganz Afrika durch innovative Technologielosungen schutzen und starken.\n\n**Wichtige Fakten**:\n- Gegrundet in Kenia, bedient den gesamten afrikanischen Kontinent\n- Spezialisiert auf Cybersicherheit, Webentwicklung, Cloud-Infrastruktur und digitale Transformation\n- Engagiert fur den Aufbau sicherer, skalierbarer und moderner Systeme\n- Team von qualifizierten Fachleuten mit Expertise in mehreren Technologiebereichen\n\n**Unser Ansatz**: Wir kombinieren tiefes technisches Know-how mit einem grundlichen Verstandnis der afrikanischen Geschaftsbedurfnisse, um Losungen zu liefern, die weltweit wettbewerbsfahig und lokal relevant sind.\n\nKontaktieren Sie uns unter tixsyncsolutions@gmail.com oder +254704440164 fur weitere Informationen.",
    },
    careers: {
      en: "We are always looking for talented individuals to join our team!\n\n**Current Opportunities**:\n- Cybersecurity Analysts\n- Full-Stack Developers\n- Cloud Engineers\n- DevOps Specialists\n- Mobile Developers\n\n**How to Apply**:\nSend your resume and cover letter to tixsyncsolutions@gmail.com with the subject line: 'Application - [Position]'\n\n**What We Offer**:\n- Competitive compensation\n- Remote work flexibility\n- Professional development opportunities\n- Work on impactful projects across Africa\n\nWe welcome applicants from all African countries. Don't hesitate to reach out!",
      sw: "Tunatafuta watu wenye vipaji daima kujiunga na timu yetu!\n\n**Nafasi za Sasa**:\n- Wachambuzi wa Ulinzi wa Mtandao\n- Wasanidi Programu wa Kamili\n- Wataalamu wa Wingu\n- Wataalamu wa DevOps\n- Wasanidi Programu wa Simu\n\n**Jinsi ya Kuomba**:\nTuma CV yako na barua ya uwasilishaji kwa tixsyncsolutions@gmail.com kwa mada: 'Ombi - [Nafasi]'\n\n**Tunachotoa**:\n- Malipo ya ushindani\n- Kufanya kazi kwa mbali kwa urahisi\n- Fursa za ukuaji wa kitaalamu\n- Kufanya kazi kwenye miradi ya athari kote Afrika\n\nTunawakaribisha waombaji kutoka nchi zote za Afrika. Usisite kuwasiliana!",
      fr: "Nous recherchons toujours des talents pour rejoindre notre equipe !\n\n**Opportunites actuelles** :\n- Analystes en cybersecurite\n- Developpeurs Full-Stack\n- Ingenieurs Cloud\n- Specialistes DevOps\n- Developpeurs Mobiles\n\n**Comment postuler** :\nEnvoyez votre CV et lettre de motivation a tixsyncsolutions@gmail.com avec l'objet : 'Candidature - [Poste]'\n\n**Ce que nous offrons** :\n- Remuneration competitive\n- Flexibilite du travail a distance\n- Opportunites de developpement professionnel\n- Travailler sur des projets impactants a travers l'Afrique\n\nNous accueillons les candidats de tous les pays africains. N'hesitez pas a nous contacter !",
      es: "Siempre buscamos personas talentosas para unirse a nuestro equipo!\n\n**Oportunidades actuales**:\n- Analistas de Ciberseguridad\n- Desarrolladores Full-Stack\n- Ingenieros de Nube\n- Especialistas en DevOps\n- Desarrolladores Moviles\n\n**Como aplicar**:\nEnvia tu CV y carta de presentacion a tixsyncsolutions@gmail.com con el asunto: 'Aplicacion - [Posicion]'\n\n**Lo que ofrecemos**:\n- Compensacion competitiva\n- Flexibilidad de trabajo remoto\n- Oportunidades de desarrollo profesional\n- Trabajar en proyectos impactantes en toda Africa\n\nDamos la bienvenida a solicitantes de todos los paises africanos. No dudes en contactarnos!",
      de: "Wir suchen immer nach talentierten Personen, um unserem Team beizutreten!\n\n**Aktuelle Moglichkeiten**:\n- Cybersicherheitsanalysten\n- Full-Stack-Entwickler\n- Cloud-Ingenieure\n- DevOps-Spezialisten\n- Mobile Entwickler\n\n**So bewerben Sie sich**:\nSenden Sie Ihren Lebenslauf und Ihr Anschreiben an tixsyncsolutions@gmail.com mit dem Betreff: 'Bewerbung - [Position]'\n\n**Was wir bieten**:\n- Wettbewerbsfahige Vergutung\n- Flexibilitat beim Remote-Arbeit\n- Moglichkeiten zur beruflichen Weiterbildung\n- Arbeit an wirkungsvollen Projekten in ganz Afrika\n\nWir begrussen Bewerber aus allen afrikanischen Landern. Zogern Sie nicht, uns zu kontaktieren!",
    },
    contact: {
      en: "You can reach TIXSYNC SOLUTIONS through multiple channels:\n\n- **Email**: tixsyncsolutions@gmail.com\n- **Phone/WhatsApp**: +254704440164\n- **Website**: tixsyncsolutions.com\n\nWe respond to all inquiries within 24 hours. For urgent matters, calling or WhatsApp is recommended.\n\nOur team is available Monday through Friday, 8:00 AM to 6:00 PM EAT (East Africa Time).",
      sw: "Unaweza kuwasiliana na TIXSYNC SOLUTIONS kupitia njia nyingi:\n\n- **Barua pepe**: tixsyncsolutions@gmail.com\n- **Simu/WhatsApp**: +254704440164\n- **Tovuti**: tixsyncsolutions.com\n\nTunajibu maswali yote ndani ya masaa 24. Kwa mambo ya dharura, inapendekeza kupiga simu au WhatsApp.\n\nTimu yetu inapatikana Jumatatu hadi Ijumaa, saa 8:00 asubuhi hadi 6:00 jioni EAT (Muda wa Afrika Mashariki).",
      fr: "Vous pouvez contacter TIXSYNC SOLUTIONS par plusieurs canaux :\n\n- **Email** : tixsyncsolutions@gmail.com\n- **Telephone/WhatsApp** : +254704440164\n- **Site web** : tixsyncsolutions.com\n\nNous repondons a toutes les demandes dans les 24 heures. Pour les urgences, il est recommande d'appeler ou d'utiliser WhatsApp.\n\nNotre equipe est disponible du lundi au vendredi, de 8h00 a 18h00 heure de l'Afrique de l'Est.",
      es: "Puedes contactar a TIXSYNC SOLUTIONS a traves de multiples canales:\n\n- **Email**: tixsyncsolutions@gmail.com\n- **Telefono/WhatsApp**: +254704440164\n- **Sitio web**: tixsyncsolutions.com\n\nRespondemos a todas las consultas dentro de 24 horas. Para asuntos urgentes, se recomienda llamar o usar WhatsApp.\n\nNuestro equipo esta disponible de lunes a viernes, 8:00 AM a 6:00 PM hora del Este de Africa.",
      de: "Sie konnen TIXSYNC SOLUTIONS uber mehrere Kanale erreichen:\n\n- **E-Mail**: tixsyncsolutions@gmail.com\n- **Telefon/WhatsApp**: +254704440164\n- **Webseite**: tixsyncsolutions.com\n\nWir beantworten alle Anfragen innerhalb von 24 Stunden. Fur dringende Angelegenheiten wird empfohlen, anzurufen oder WhatsApp zu nutzen.\n\nUnser Team ist von Montag bis Freitag, 8:00 bis 18:00 Uhr Ostafrikanische Zeit verfugbar.",
    },
    web: {
      en: "We build modern, high-performance web applications:\n\n- **Frontend**: React, Next.js, TypeScript, Tailwind CSS\n- **Backend**: Node.js, Python, Express, REST APIs, GraphQL\n- **Databases**: PostgreSQL, MongoDB, Redis\n- **Specialties**: E-commerce platforms, SaaS applications, corporate websites, progressive web apps\n\nOur web solutions are built for performance, scalability, and security. We follow modern best practices including responsive design, SEO optimization, and automated testing.\n\nInterested in a web project? Contact us at tixsyncsolutions@gmail.com.",
      sw: "Tunaunda programu za wavuti za kisasa, za utendaji mkubwa:\n\n- **Mbele**: React, Next.js, TypeScript, Tailwind CSS\n- **Nyuma**: Node.js, Python, Express, REST APIs, GraphQL\n- **Hifadhidata**: PostgreSQL, MongoDB, Redis\n- **Maarifa**: Majukwaa ya biashara, programu za SaaS, tovuti za kampuni, programu za hatua za pembeni\n\nSuluhisho zetu za wavuti zimejengwa kwa utendaji, kupanuka, na usalama. Tunafuata mazoea bora ya kisasa ikiwa ni pamoja na muundo unaobadilika, uboreshaji wa SEO, na upimaji wa kiotomatiki.\n\nUnapendelea mradi wa wavuti? Tuandikie kwa tixsyncsolutions@gmail.com.",
      fr: "Nous developpons des applications web modernes et performantes :\n\n- **Frontend** : React, Next.js, TypeScript, Tailwind CSS\n- **Backend** : Node.js, Python, Express, REST APIs, GraphQL\n- **Bases de donnees** : PostgreSQL, MongoDB, Redis\n- **Specialites** : Plates-formes e-commerce, applications SaaS, sites d'entreprise, applications web progressives\n\nNos solutions web sont concues pour la performance, l'evolutivite et la securite. Nous suivons les meilleures pratiques modernes, y compris le design responsive, l'optimisation SEO et les tests automatises.\n\nInteresse par un projet web ? Contactez-nous a tixsyncsolutions@gmail.com.",
      es: "Construimos aplicaciones web modernas y de alto rendimiento:\n\n- **Frontend**: React, Next.js, TypeScript, Tailwind CSS\n- **Backend**: Node.js, Python, Express, REST APIs, GraphQL\n- **Bases de datos**: PostgreSQL, MongoDB, Redis\n- **Especialidades**: Plataformas e-commerce, aplicaciones SaaS, sitios web corporativos, aplicaciones web progresivas\n\nNuestras soluciones web estan construidas para rendimiento, escalabilidad y seguridad. Seguimos las mejores practicas modernas, incluyendo diseno responsivo, optimizacion SEO y pruebas automatizadas.\n\nInteresado en un proyecto web? Contactanos en tixsyncsolutions@gmail.com.",
    },
    cloud: {
      en: "Our cloud infrastructure services help you leverage the power of cloud computing:\n\n- **Cloud Platforms**: AWS, Microsoft Azure, Google Cloud Platform\n- **Migration**: Seamless migration from on-premises to cloud\n- **Architecture**: Serverless, microservices, containerized solutions\n- **Management**: Docker, Kubernetes, monitoring, optimization\n- **Security**: Cloud security assessments, compliance, best practices\n\nWe help businesses reduce costs, improve scalability, and increase reliability through cloud adoption.\n\nReady to move to the cloud? Contact us at tixsyncsolutions@gmail.com.",
      sw: "Huduma zetu za miundombinu ya wingu zinakusaidia kutumia nguvu ya komputa ya wingu:\n\n- **Mifumo ya Wingu**: AWS, Microsoft Azure, Google Cloud Platform\n- **Uhamishaji**: Uhamishaji rahisi kutoka ndani hadi wingu\n- **Usanidi**: Bila huduma, huduma ndogo, suluhisho zilizowekwa kwenye chombo\n- **Usimamizi**: Docker, Kubernetes, ufuatiliaji, uboreshaji\n- **Ulinzi**: Tathmini za usalama wa wingu, uzingatiaji, mazoea bora\n\nTunawasaidia biashara kupunguza gharama, kuboresha uwezo wa kupanuka, na kuongeza uaminifu kupitia ukubali wa wingu.\n\nUko tayari kuhamia wingu? Tuandikie kwa tixsyncsolutions@gmail.com.",
      fr: "Nos services d'infrastructure cloud vous aident a exploiter la puissance de l'informatique en nuage :\n\n- **Plateformes Cloud** : AWS, Microsoft Azure, Google Cloud Platform\n- **Migration** : Migration fluide du local vers le cloud\n- **Architecture** : Serverless, microservices, solutions conteneurisees\n- **Gestion** : Docker, Kubernetes, surveillance, optimisation\n- **Securite** : Evaluations de securite cloud, conformite, meilleures pratiques\n\nNous aidons les entreprises a reduire les couts, ameliorer l'evolutivite et augmenter la fiabilite grace a l'adoption du cloud.\n\nPret a migrer vers le cloud ? Contactez-nous a tixsyncsolutions@gmail.com.",
    },
    devops: {
      en: "Our DevOps services streamline your development and deployment processes:\n\n- **CI/CD Pipelines**: Automated build, test, and deployment workflows\n- **Tools**: GitHub Actions, Jenkins, GitLab CI, CircleCI\n- **Infrastructure as Code**: Terraform, Ansible, CloudFormation\n- **Containerization**: Docker, Kubernetes, Docker Compose\n- **Monitoring**: Prometheus, Grafana, ELK Stack\n- **Benefits**: Faster releases, fewer bugs, improved collaboration\n\nWe help teams adopt DevOps practices to deliver software faster and more reliably.\n\nWant to optimize your workflow? Contact us at tixsyncsolutions@gmail.com.",
      sw: "Huduma zetu za DevOps zinarahisisha michakato yako ya uundaji na uwekaji:\n\n- **Mitirio ya CI/CD**: Mifumo ya kiotomatiki ya kujenga, kupima, na kuweka\n- **Zana**: GitHub Actions, Jenkins, GitLab CI, CircleCI\n- **Miundombinu kama Kanuni**: Terraform, Ansible, CloudFormation\n- **Uwekaji kwenye Chombo**: Docker, Kubernetes, Docker Compose\n- **Ufuatiliaji**: Prometheus, Grafana, ELK Stack\n- **Faida**: Utoaji wa haraka, hiti kidogo, uboreshaji wa ushirikiano\n\nTunawasaidia timu kupitisha mazoea ya DevOps ili kutoa programu kwa haraka na kwa uaminifu zaidi.\n\nUnataka kuboresha mtiririko wako wa kazi? Tuandikie kwa tixsyncsolutions@gmail.com.",
    },
    mobile: {
      en: "We develop cross-platform mobile applications that feel native:\n\n- **Frameworks**: React Native, Flutter\n- **Platforms**: iOS and Android from a single codebase\n- **Features**: Push notifications, offline support, camera integration, payments\n- **Performance**: Near-native performance with code reuse\n- **Deployment**: App Store and Google Play submission assistance\n\nOur mobile apps are designed for performance, beautiful UI, and seamless user experience.\n\nHave a mobile app idea? Contact us at tixsyncsolutions@gmail.com.",
      sw: "Tunaunda programu za simu za mezani ambazo zinahisia asili:\n\n- **Mifumo**: React Native, Flutter\n- **Mifumo**: iOS na Android kutoka msingi mmoja wa kanuni\n- **Vipengele**: Arifa za push, msaada wa nje ya mtandao, muunganisho wa kamera, malipo\n- **Utendaji**: Utendaji wa karibu na asili na matumizi ya kanuni tena\n- **Uwekaji**: Msaada wa kuwasilisha Programu ya App na Google Play\n\nProgramu zetu za simu zimeundwa kwa utendaji, UI nzuri, na uzoefu laini wa mtumiaji.\n\nUna dhidi ya programu ya simu? Tuandikie kwa tixsyncsolutions@gmail.com.",
    },
    digital: {
      en: "Our Digital Transformation services help you modernize your business:\n\n- **Process Automation**: Streamline repetitive tasks with smart workflows\n- **System Integration**: Connect disparate systems for seamless data flow\n- **Data Analytics**: Turn raw data into actionable business insights\n- **Workflow Optimization**: Improve efficiency and reduce bottlenecks\n- **Change Management**: Smooth transition to new digital processes\n\nWe help organizations across Africa embrace digital tools to stay competitive.\n\nReady to transform your business? Contact us at tixsyncsolutions@gmail.com.",
      sw: "Huduma zetu za Mabadiliko ya Dijitali zinakusaidia kusasisha biashara yako:\n\n- **Uboreshaji wa Mchakato**: Rahisisha majukwa ya kurudia kwa mtiririko wa kazi wa busara\n- **Muunganisho wa Mifumo**: Unganisha mifumo tofauti kwa mtiririko laini wa data\n- **Uchambuzi wa Data**: Geuza data ghafi kuwa maarifa ya biashara\n- **Uboreshaji wa Mtiririko wa Kazi**: Boresha ufanisi na kupunguza vikwazo\n- **Usimamizi wa Mabadiliko**: Mabadiliko laini ya mchakato mpya wa kidijitali\n\nTunawasaidia mashirika kote Afrika kukubali zana za kidijitali ili kubaki katika ushindani.\n\nUko tayari kubadilisha biashara yako? Tuandikie kwa tixsyncsolutions@gmail.com.",
    },
    compliance: {
      en: "We help organizations achieve and maintain compliance with global standards:\n\n- **ISO 27001**: Information Security Management System certification\n- **GDPR**: European data protection regulation compliance\n- **Security Audits**: Comprehensive assessment of compliance posture\n- **Policy Development**: Creating security policies and procedures\n- **Training**: Staff awareness and compliance training programs\n\nCompliance is not just about meeting requirements - it's about building trust with your customers and partners.\n\nNeed compliance assistance? Contact us at tixsyncsolutions@gmail.com.",
      sw: "Tunawasaidia mashirika kufikia na kudumisha uzingatiaji wa viwango vya kimataifa:\n\n- **ISO 27001**: Usajili wa Mfumo wa Usimamizi wa Usalama wa Taarifa\n- **GDPR**: Kufuata kanuni za ulinzi wa data za Ulaya\n- **Ukaguzi wa Usalama**: Tathmini kamili ya hali ya uzingatiaji\n- **Maendeleo ya Sera**: Kuunda sera na taratibu za usalama\n- **Mafunzo**: Programu za uelewa wa wafanyakazi na mafunzo ya uzingatiaji\n\nUzingatiaji si tu kuhusu kuf mahitaji - ni kuhusu kujenga uaminifu na wateja na washirika wako.\n\nUnahitaji msaada wa uzingatiaji? Tuandikie kwa tixsyncsolutions@gmail.com.",
    },
    fallback: {
      en: "That's a great question! While I may not have a specific answer for that, I'd recommend reaching out to our team directly at tixsyncsolutions@gmail.com or calling +254704440164 for personalized assistance. Is there anything specific about our services I can help with?",
      sw: "Hiyo ni swali zuri! Ingawa sina jibu maalum kwa hilo, ningependekeza kuwasiliana na timu yetu moja kwa moja kwa tixsyncsolutions@gmail.com au kupiga +254704440164 kwa msaada maalum. Kuna chochote maalum kuhusu huduma zetu ninachoweza kukusaidia?",
      fr: "C'est une excellente question ! Bien que je n'aie pas de reponse specifique a cela, je vous recommande de contacter directement notre equipe a tixsyncsolutions@gmail.com ou d'appeler le +254704440164 pour une assistance personnalisee. Y a-t-il quelque chose de specifique concernant nos services avec laquelle je peux vous aider ?",
      es: "Buena pregunta! Aunque no tengo una respuesta especifica para eso, te recomiendo contactar a nuestro equipo directamente en tixsyncsolutions@gmail.com o llamar al +254704440164 para asistencia personalizada. Hay algo especifico sobre nuestros servicios en lo que pueda ayudarte?",
      de: "Das ist eine tolle Frage! Obwohl ich darauf keine spezifische Antwort habe, empfehle ich, direkt Kontakt mit unserem Team aufzunehmen unter tixsyncsolutions@gmail.com oder +254704440164 fur personliche Hilfe. Gibt es etwas Bestimmtes uber unsere Dienstleistungen, bei dem ich helfen kann?",
    },
    thanks: {
      en: "You're welcome! Feel free to reach out anytime at tixsyncsolutions@gmail.com or +254704440164. Have a great day!",
      sw: "Karibu! Usisite kuwasiliana wakati wowote kwa tixsyncsolutions@gmail.com au +254704440164. Uwe na siku njema!",
      fr: "De rien ! N'hesitez pas a nous contacter a tout moment a tixsyncsolutions@gmail.com ou +254704440164. Excellente journee !",
      es: "De nada! No dudes en contactarnos en cualquier momento en tixsyncsolutions@gmail.com o +254704440164. Que tengas un excelente dia!",
      de: "Gern geschehen! Kontaktieren Sie uns jederzeit unter tixsyncsolutions@gmail.com oder +254704440164. Einen schonen Tag noch!",
    },
    help: {
      en: "I can help you with information about:\n\n- **Our Services**: Cybersecurity, Web Development, Cloud, Digital Transformation, Compliance, DevOps, Mobile\n- **Pricing**: Starting from KES 50,000\n- **Company Info**: Founded by Cornelius Maina Nyaga in Kenya\n- **Careers**: Always looking for talent\n- **Contact**: tixsyncsolutions@gmail.com or +254704440164\n\nWhat would you like to know?",
      sw: "Ninaweza kukusaidia kwa taarifa kuhusu:\n\n- **Huduma zetu**: Ulinzi wa Mtandao, Uundaji wa Vavuti, Wingu, Mabadiliko ya Dijitali, Uzingatiaji, DevOps, Simu\n- **Bei**: Kuanzia KES 50,000\n- **Taarifa za Kampuni**: Ilianzishwa na Cornelius Maina Nyaga nchini Kenya\n- **Kazi**: Tunatafuta talanta daima\n- **Wasiliana**: tixsyncsolutions@gmail.com au +254704440164\n\nUngependa kujua nini?",
      fr: "Je peux vous aider avec des informations sur :\n\n- **Nos services** : Cybersecurite, Developpement Web, Cloud, Transformation Numerique, Conformite, DevOps, Mobile\n- **Tarifs** : A partir de 50 000 KES\n- **Informations sur l'entreprise** : Fondee par Cornelius Maina Nyaga au Kenya\n- **Carrieres** : Nous recherchons toujours des talents\n- **Contact** : tixsyncsolutions@gmail.com ou +254704440164\n\nQue souhaitez-vous savoir ?",
    },
    team: {
      en: "TIXSYNC SOLUTIONS was founded by Cornelius Maina Nyaga, a passionate technologist based in Kenya.\n\n**About Cornelius**:\n- Full-Stack Developer and Cybersecurity Expert\n- Founder of TIXSYNC SOLUTIONS and TIXSYNC Media\n- Specializes in building secure, scalable technology solutions\n- Based in Kenya, serving clients across Africa\n\n**Our Team**:\nWe have a growing team of skilled professionals in cybersecurity, web development, cloud architecture, and digital transformation.\n\nWant to know more? Contact us at tixsyncsolutions@gmail.com.",
      sw: "TIXSYNC SOLUTIONS ilianzishwa na Cornelius Maina Nyaga, mtaalamu wa teknolojia aliye na shauku nchini Kenya.\n\n**Kuhusu Cornelius**:\n- Msanidi Programu wa Kamili na Mtaalamu wa Ulinzi wa Mtandao\n- Mwanzilishi wa TIXSYNC SOLUTIONS na TIXSYNC Media\n- Maalum katika kujenga suluhisho za teknolojia salama, zinazoweza kupanuliwa\n- Yeye yuko Kenya, anayehudumia wateja kote Afrika\n\n**Timu yetu**:\nTuna timu inayokua ya wataalamu wenye ujuzi katika ulinzi wa mtandao, uundaji wa wavuti, usanidi wa wingu, na mabadiliko ya kidijitali.\n\nUngependa kujua zaidi? Tuandikie kwa tixsyncsolutions@gmail.com.",
    },
    security: {
      en: "Security is at the core of everything we do at TIXSYNC SOLUTIONS.\n\n**Our Security Expertise**:\n- Penetration Testing and Vulnerability Assessments\n- Security Operations Center (SOC) Management\n- Incident Response and Digital Forensics\n- SIEM Implementation and Monitoring\n- Security Policy Development\n- Compliance Auditing (ISO 27001, GDPR)\n\nWe help organizations identify and mitigate security risks before they become breaches.\n\nNeed a security assessment? Contact us at tixsyncsolutions@gmail.com.",
      sw: "Usalama uko katikati ya kila kitu tunachofanya katika TIXSYNC SOLUTIONS.\n\n**Utaalamu wetu wa Usalama**:\n- Majaribio ya Uvamizi na Tathmini za Upvu\n- Usimamizi wa Kituo cha Ulinzi wa Usalama (SOC)\n- Mshughulikiajo wa Matukio na Uchunguzi wa Dijitali\n- Uwekaji na Ufuatiliaji wa SIEM\n- Maendeleo ya Sera ya Usalama\n- Ukaguzi wa Uzingatiaji (ISO 27001, GDPR)\n\nTunawasaidia mashirika kutambua na kupunguza hatari za usalama kabla hazijakuwa ukiukaji.\n\nUnahitaji tathmini ya usalama? Tuandikie kwa tixsyncsolutions@gmail.com.",
    },
    ai: {
      en: "We integrate AI and Machine Learning solutions into business processes:\n\n- **AI Strategy**: Identifying opportunities for AI implementation\n- **Machine Learning Models**: Custom models for prediction and classification\n- **Natural Language Processing**: Chatbots, text analysis, sentiment analysis\n- **Computer Vision**: Image recognition, object detection\n- **AI-Powered Automation**: Intelligent workflow automation\n\nAI can transform how your business operates. Let us help you explore the possibilities.\n\nContact us at tixsyncsolutions@gmail.com to discuss AI solutions.",
      sw: "Tunaingiza suluhisho za AI na Ufunzaji wa Mashine kwenye mchakato wa biashara:\n\n- **Mkakati wa AI**: Kutambua fursa za utekelezaji wa AI\n- **Mifano ya Ufunzaji wa Mashine**: Mifano maalum ya utabiri na uainishaji\n- **Usindikaji wa Lugha ya Asili**: Programu za mazungumzo, uchambuzi wa maandishi, uchambuzi hisia\n- **Mtazamo wa Kompyuta**: Utambuzi wa picha, ugunduzi wa vitu\n- **Uboreshaji unaotumia AI**: Uboreshaji wa kazi wenye akili\n\nAI inaweza kubadilisha jinsi biashara yako inavyofanya kazi. Tukuruhusu kukusaidia kuchunguza uwezekano.\n\nTuandikie kwa tixsyncsolutions@gmail.com kujadili suluhisho za AI.",
    },
  };

  const response = responses[intent];
  if (!response) return responses.fallback?.en || "I can help you with that. Please contact us at tixsyncsolutions@gmail.com.";
  return response[lang] || response.en || responses.fallback?.en || "I can help you with that. Please contact us at tixsyncsolutions@gmail.com.";
}

export const INTENT_PATTERNS: IntentPattern[] = [
  { intent: "greeting", priority: 10, keywords: [/\b(hello|hi|hey|good morning|good afternoon|good evening|howdy|whats up|sup)\b/i] },
  { intent: "thanks", priority: 10, keywords: [/\b(thanks?|thank you|bye|goodbye|see you|cheers|appreciate)\b/i] },
  { intent: "help", priority: 9, keywords: [/\b(help|what can|how|what do you|assist|support)\b/i] },
  { intent: "pricing", priority: 8, keywords: [/\b(pricing|cost|price|how much|quote|rate|affordable|budget|expensive|cheap|package|plan)\b/i] },
  { intent: "contact", priority: 8, keywords: [/\b(contact|email|phone|reach|get in touch|call|whatsapp|message|reach out)\b/i] },
  { intent: "careers", priority: 8, keywords: [/\b(career|job|jobs|hiring|hire|recruit|vacancy|work with|join|team|apply)\b/i] },
  { intent: "about", priority: 8, keywords: [/\b(about|who|team|founder|cornelius|company|story|background|history|mission)\b/i] },
  { intent: "cybersecurity", priority: 7, keywords: [/\b(cybersecurity|security|penetration|soc|firewall|siem|incident|vulnerability|hack|breach|encrypt|malware|phishing|threat|risk|audit|protect)\b/i] },
  { intent: "web", priority: 7, keywords: [/\b(web\s*(dev|develop|development)|react|next\.?js|node\.?js|typescript|python|full.?stack|website|web app|frontend|backend|api|database|ecommerce)\b/i] },
  { intent: "cloud", priority: 7, keywords: [/\b(cloud|aws|azure|gcp|migration|serverless|docker|kubernetes|infrastructure|hosting|deploy|scale)\b/i] },
  { intent: "devops", priority: 7, keywords: [/\b(devops|ci\/cd|pipeline|terraform|ansible|jenkins|github actions|automation|deploy|release|build)\b/i] },
  { intent: "mobile", priority: 7, keywords: [/\b(mobile|app|react native|flutter|ios|android|smartphone|phone app)\b/i] },
  { intent: "digital", priority: 7, keywords: [/\b(digital|transform|modernize|automation|modern|workflow|process|integration)\b/i] },
  { intent: "compliance", priority: 7, keywords: [/\b(compliance|iso|gdpr|regulation|audit|standard|policy|certif)\b/i] },
  { intent: "ai", priority: 6, keywords: [/\b(ai|artificial intelligence|machine learning|ml|neural|deep learning|nlp|chatbot|automation|intelligent)\b/i] },
  { intent: "security", priority: 6, keywords: [/\b(secure|safety|protect|defend|guard|shield|risk|threat|attack|data protection)\b/i] },
  { intent: "team", priority: 6, keywords: [/\b(team|staff|people|employee|member|engineer|developer|expert|specialist|leader)\b/i] },
];

export function matchIntent(text: string): { intent: string; priority: number } {
  const lower = text.toLowerCase();
  let best = { intent: "fallback", priority: 0 };
  for (const pattern of INTENT_PATTERNS) {
    if (pattern.priority <= best.priority) continue;
    for (const keyword of pattern.keywords) {
      if (keyword.test(lower)) {
        best = { intent: pattern.intent, priority: pattern.priority };
        break;
      }
    }
  }
  return best;
}
